An error occurred while executing the following cell:
------------------
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

try:
    import torch
except ModuleNotFoundError:
    %pip install -qq torch
    import torch

try:
    from torchvision.utils import make_grid
except ModuleNotFoundError:
    %pip install -qq torchvision
    from torchvision.utils import make_grid

import torch.nn as nn
from torchvision.datasets import MNIST
import torch.nn.functional as F
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

try:
    from pytorch_lightning import LightningModule, Trainer
except ModuleNotFoundError:
    %pip install -qq pytorch-lightning
    from pytorch_lightning import LightningModule, Trainer

try:
    from einops import rearrange
except ModuleNotFoundError:
    %pip install -qq einops
    from einops import rearrange

try:
    import probml_utils
except ModuleNotFoundError:
    %pip install -qq git+https://github.com/probml/probml-utils.git
    import probml_utils

from probml_utils import savefig

from probml_utils.lvm_plots_utils import (
    get_random_samples,
    get_grid_samples,
    plot_scatter_plot,
    get_imrange,
    plot_grid_plot,
    plot_scatter_plot,
)

import seaborn as sns
from torchvision.utils import make_grid
from probml_utils.vae_conv_mnist import ConvVAE

%pip install -qq test-tube umap
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_5354/3536696859.py in <module>
     23 try:
---> 24     from pytorch_lightning import LightningModule, Trainer
     25 except ModuleNotFoundError:

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/__init__.py in <module>
     29 
---> 30 from pytorch_lightning.callbacks import Callback  # noqa: E402
     31 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py in <module>
     13 # limitations under the License.
---> 14 from pytorch_lightning.callbacks.base import Callback
     15 from pytorch_lightning.callbacks.device_stats_monitor import DeviceStatsMonitor

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/callbacks/base.py in <module>
     24 import pytorch_lightning as pl
---> 25 from pytorch_lightning.utilities.types import STEP_OUTPUT
     26 

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/__init__.py in <module>
     17 
---> 18 from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
     19 from pytorch_lightning.utilities.distributed import AllGatherGrad  # noqa: F401

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py in <module>
     28 from pytorch_lightning.utilities.exceptions import MisconfigurationException
---> 29 from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
     30 from pytorch_lightning.utilities.warnings import rank_zero_deprecation

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/imports.py in <module>
    125 
--> 126 from pytorch_lightning.utilities.xla_device import XLADeviceUtils  # noqa: E402
    127 

ModuleNotFoundError: No module named 'pytorch_lightning.utilities.xla_device'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_5354/3536696859.py in <module>
     25 except ModuleNotFoundError:
     26     get_ipython().run_line_magic('pip', 'install -qq pytorch-lightning')
---> 27     from pytorch_lightning import LightningModule, Trainer
     28 
     29 try:

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/__init__.py in <module>
     28     _logger.propagate = False
     29 
---> 30 from pytorch_lightning.callbacks import Callback  # noqa: E402
     31 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402
     32 from pytorch_lightning.trainer import Trainer  # noqa: E402

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.callbacks.base import Callback
     15 from pytorch_lightning.callbacks.device_stats_monitor import DeviceStatsMonitor
     16 from pytorch_lightning.callbacks.early_stopping import EarlyStopping

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/callbacks/base.py in <module>
     23 
     24 import pytorch_lightning as pl
---> 25 from pytorch_lightning.utilities.types import STEP_OUTPUT
     26 
     27 

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/__init__.py in <module>
     16 import numpy
     17 
---> 18 from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
     19 from pytorch_lightning.utilities.distributed import AllGatherGrad  # noqa: F401
     20 from pytorch_lightning.utilities.enums import (  # noqa: F401

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py in <module>
     27 
     28 from pytorch_lightning.utilities.exceptions import MisconfigurationException
---> 29 from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
     30 from pytorch_lightning.utilities.warnings import rank_zero_deprecation
     31 

~/miniconda3/envs/py37/lib/python3.7/site-packages/pytorch_lightning/utilities/imports.py in <module>
    124 
    125 
--> 126 from pytorch_lightning.utilities.xla_device import XLADeviceUtils  # noqa: E402
    127 
    128 _TPU_AVAILABLE = XLADeviceUtils.tpu_device_exists()

ModuleNotFoundError: No module named 'pytorch_lightning.utilities.xla_device'
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.xla_device'
